# Generated by Django 3.0.5 on 2020-04-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('auther', models.CharField(max_length=50)),
            ],
        ),
    ]
